# Generated by Django 5.0.6 on 2024-09-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteLedger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedpdf',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='file_name',
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='cid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
