# Generated by Django 5.0.6 on 2024-09-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteLedger', '0002_rename_upload_date_uploadedpdf_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='title',
            field=models.CharField(blank=True, default='mynotes', max_length=255, null=True),
        ),
    ]
